"""Add description and priority to model

Revision ID: ac5e9b0117e0
Revises: 4db88ed1ca37
Create Date: 2024-08-03 01:17:29.326190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac5e9b0117e0'
down_revision = '4db88ed1ca37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('to_do', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('priority', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('to_do', schema=None) as batch_op:
        batch_op.drop_column('priority')
        batch_op.drop_column('description')

    # ### end Alembic commands ###
